#!/usr/bin/env bash
source colors.sh
PARENT_REMOTE=$1
if [ -z "${PARENT_REMOTE}" ]; then
	PARENT_REMOTE="upstream"
fi

CURRENT_BRANCH=`git symbolic-ref --short HEAD`
echo -e ${ORANGE}"Current Branch: "${NC}${CURRENT_BRANCH}
echo -e ${ORANGE}'Pulling changes from upstream'${NC}
git pull --rebase ${PARENT_REMOTE} ${CURRENT_BRANCH}

